### ISSUE TITLE
Would a class for the entire slot structure usefull?

### ISSUE THREAD

**Issue by MinekPo1** [walksanatora/HAsave-reader#3]
I have started implementing it (see [this branch](https://github.com/MinekPo1/HAsave-reader/tree/HASlot)), but Im not sure if it would be usefull. It potentially could have helper functions and/or tools for aggregation of chunk files ect.

**Comment by walksanatora** [comment]
i think implementing classes would make it easier to write editors and it seems like a good feature to add. so I will accept if you pr this

**Comment by MinekPo1** [comment]
PR has been made. See #4. Closing this thread.
